services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        ports:
            - "8080:8080"
        command: php artisan serve --host=0.0.0.0 --port=8080
        depends_on:
            - mysql
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        networks:
            - laravel

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-queue
        volumes:
            - .:/var/www/html
        command: php artisan queue:work --timeout=1800 --tries=3
        depends_on:
            - app
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        networks:
            - laravel

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-scheduler
        volumes:
            - .:/var/www/html
        command: php artisan schedule:work
        depends_on:
            - app
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
